# Dataquest 2023 Preliminary: PyCaret regression model comparison on the cleaned training data

In [ ]:
!pip install pycaret

In [ ]:
import gdown
from pycaret.regression import *
import pandas as pd

DATA_DIR = "../data"

In [ ]:
url = 'https://drive.google.com/u/1/uc?id=1aHehuaIz-7caH83d6DWmOKsFkz6w9JrQ'
output = f"{DATA_DIR}/train_cleaned.csv"
gdown.download(url, output, quiet=False)

Downloading...
From: https://drive.google.com/u/1/uc?id=1aHehuaIz-7caH83d6DWmOKsFkz6w9JrQ
To: /content/train_cleaned.csv
100%|██████████| 35.5M/35.5M [00:00<00:00, 153MB/s]

'train_cleaned.csv'

In [ ]:
train_df = pd.read_csv(f"{DATA_DIR}/train_cleaned.csv")
train_df.head()

,datetime,temp,d_point,feels,min_temp,max_temp,prssr,hum,wind_spd,wind_deg,rain_1h,clouds,year,month,week,day,hour,dayofweek
0,1979-01-01 00:00:00,24.75,23.89,25.76,24.28,25.22,1012.0,0.0095,0.82,320.0,0.00,0.0100,1979,1,1,1,0,0
1,1979-01-01 01:00:00,24.58,23.73,25.57,23.99,25.26,1012.0,0.0095,0.96,338.0,0.00,0.0100,1979,1,1,1,1,0
2,1979-01-01 02:00:00,26.60,24.06,26.60,26.10,27.39,1012.0,0.0086,1.22,339.0,0.00,0.0099,1979,1,1,1,2,0
3,1979-01-01 03:00:00,27.31,24.37,30.90,26.59,28.36,1012.0,0.0084,1.08,342.0,0.13,0.0094,1979,1,1,1,3,0
4,1979-01-01 04:00:00,27.41,25.05,31.54,26.58,28.31,1011.0,0.0087,0.86,336.0,0.34,0.0100,1979,1,1,1,4,0

In [ ]:
s = setup(
    data=train_df,
    target="rain_1h",
    session_id=42,
    use_gpu=True
)

In [ ]:
best_model = compare_models()

In [ ]:
evaluate_model(best_model)

In [ ]:
predict_model(best_model)

,datetime,temp,d_point,feels,min_temp,max_temp,prssr,hum,wind_spd,wind_deg,clouds,year,month,week,day,hour,dayofweek,rain_1h,prediction_label
233879,2007-06-19 20:00:00,25.280001,24.600000,26.370001,24.379999,26.620001,1005.0,0.0096,1.62,217.0,0.0056,2007,6,25,19,20,1,0.00,0.298862
209653,2004-07-07 06:00:00,27.900000,24.540001,32.150002,26.820000,28.350000,1009.0,0.0082,1.32,45.0,0.0089,2004,7,28,7,6,2,0.93,0.432811
7143,1979-11-14 06:00:00,26.379999,24.969999,26.379999,25.250000,31.020000,1008.0,0.0092,1.48,124.0,0.0100,1979,11,46,14,6,2,0.68,0.424888
167683,1999-05-31 22:00:00,24.290001,23.260000,25.230000,23.070000,26.110001,1012.0,0.0094,2.09,231.0,0.0050,1999,5,22,31,22,0,0.00,0.280104
193405,2002-07-16 03:00:00,29.100000,22.830000,32.759998,27.920000,31.020000,1012.0,0.0069,1.69,144.0,0.0033,2002,7,29,16,3,1,0.13,0.455520
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
217378,2005-06-17 04:00:00,29.700001,26.290001,36.700001,29.040001,30.450001,1009.0,0.0082,1.65,135.0,0.0047,2005,6,24,17,4,4,0.00,0.449910
213067,2004-12-08 07:00:00,29.860001,24.490000,35.419998,29.570000,30.340000,1008.0,0.0073,2.27,235.0,0.0100,2004,12,50,8,7,2,1.23,0.417262
12382,1980-07-02 14:00:00,25.379999,23.620001,26.320000,24.559999,26.760000,1010.0,0.0090,2.37,196.0,0.0039,1980,7,27,2,14,2,0.00,0.352424
98194,1990-12-09 15:00:00,24.820000,24.650000,25.940001,24.280001,25.730000,1010.0,0.0099,1.08,192.0,0.0093,1990,12,49,9,15,6,0.00,0.342439
203268,2003-09-30 06:00:00,30.969999,23.620001,36.080002,29.620001,32.410000,1007.0,0.0065,2.78,180.0,0.0100,2003,9,40,30,6,1,0.00,0.429248