In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/ristek-datathon-2022/unlabeled.csv
/kaggle/input/ristek-datathon-2022/sample_submission.csv
/kaggle/input/ristek-datathon-2022/train.csv
/kaggle/input/ristek-datathon-2022/test.csv
/kaggle/input/ristek-datathon-2022/media/Image/ENxfP4KVUAAcBgY.jpg
/kaggle/input/ristek-datathon-2022/media/Image/ERmtSP3XYAI1F1S.jpg
/kaggle/input/ristek-datathon-2022/media/Image/ENL8ySWU4AAYyPD.jpg
/kaggle/input/ristek-datathon-2022/media/Image/ENLO-FfVAAE_QbS.jpg
/kaggle/input/ristek-datathon-2022/media/Image/EOEUS2HVAAAGJ6m.jpg
/kaggle/input/ristek-datathon-2022/media/Image/ERlrAJYUwAAy7r_.jpg
/kaggle/input/ristek-datathon-2022/media/Image/ENc3wKTU0AA1KUQ.jpg
/kaggle/input/ristek-datathon-2022/media/Image/EQzXprHVUAA2F7V.jpg
/kaggle/input/ristek-datathon-2022/media/Image/ENK2epKU4AALRt5.jpg
/kaggle/input/ristek-datathon-2022/media/Image/ENW2TOLU8AEwPJw.jpg
/kaggle/input/ristek-datathon-2022/media/Image/EN1rpdTVAAASEGr.jpg
/kaggle/input/ristek-datathon-2022/media/Image/ENf_a1oU8AAKEF_.jpg
/kaggle/input/ristek-datathon-2022/media/Image/ERnBkrBVUAAx7ZW.jpg
/kaggle/input/ristek-datathon-2022/media/Image/ENQ8mlZU8AArx1U.jpg
/kaggle/input/ristek-datathon-2022/media/Image/ERkyYpmUwAAXWRt.jpg
/kaggle/input/ristek-datathon-2022/media/Image/ENQaJVOUEAAP0ac.jpg
/kaggle/input/ristek-datathon-2022/media/Image/ENPtN21U4AAxAe-.jpg
/kaggle/input/ristek-datathon-2022/media/Image/ENRlRaKU0AEiPgG.jpg
/kaggle/input/ristek-datathon-2022/media/Image/ENgnCMzU4AAdnJ_.jpg
/kaggle/input/ristek-datathon-2022/media/Image/EOBpEHjUwAATVVT.jpg
/kaggle/input/ristek-datathon-2022/media/Image/ENbHD06UYAAp-QU.jpg
/kaggle/input/ristek-datathon-2022/media/Image/ENqEMKLVUAAE9p-.jpg
/kaggle/input/ristek-datathon-2022/media/Image/ERbcNpOVUAIK_hk.jpg
/kaggle/input/ristek-datathon-2022/media/Image/EOEl3HrU0AAWhki.jpg
/kaggle/input/ristek-datathon-2022/media/Image/ERauZ31WoAM8xBD.jpg
/kaggle/input/ristek-datathon-2022/media/Image/ENv8D5UU4AA04X6.jpg
/kaggle/input/ristek-datathon-2022/media/Image/ENPz1auUcAU-Zcg.jpg
/kaggle/input/ristek-datathon-2022/media/Image/ENqMXzOU0AAxACW.jpg
/kaggle/input/ristek-datathon-2022/media/Image/EN-QSNcVUAA_rD3.jpg
/kaggle/input/ristek-datathon-2022/media/Image/ENPMm8KVAAAIvFw.jpg
/kaggle/input/ristek-datathon-2022/media/Image/ERdmxbrUcAEfoQv.jpg
/kaggle/input/ristek-datathon-2022/media/Image/ENKXS5RU8AAte2Z.jpg
/kaggle/input/ristek-datathon-2022/media/Image/ERlVaftVUAASGGt.jpg
/kaggle/input/ristek-datathon-2022/media/Image/ERlS6LHUUAA3h_C.jpg
/kaggle/input/ristek-datathon-2022/media/Image/EN61JUCVAAM-mJs.jpg
/kaggle/input/ristek-datathon-2022/media/Image/ERcyrLPU8AEz81v.jpg
/kaggle/input/ristek-datathon-2022/media/Image/ESVHebNXYAAwRle.jpg
/kaggle/input/ristek-datathon-2022/media/Image/ERZrnkdU0AAk6wP.jpg
/kaggle/input/ristek-datathon-2022/media/Image/ELy3m3_UUAABWix.jpg
/kaggle/input/ristek-datathon-2022/media/Image/EPkglHhUUAAKrJl.jpg
/kaggle/input/ristek-datathon-2022/media/Image/EMwYwiKUwAA8p9t.jpg
/kaggle/input/ristek-datathon-2022/media/Image/ENf8LCYUEAAgoc0.jpg
/kaggle/input/ristek-datathon-2022/media/Image/ENL8TAlU0AIWHgC.jpg
/kaggle/input/ristek-datathon-2022/media/Image/ENrNfiWVAAAvY-I.jpg
/kaggle/input/ristek-datathon-2022/media/Image/EOPchJ6UcAADzac.jpg
/kaggle/input/ristek-datathon-2022/media/Image/ENLqkKvU0AAX58x.jpg
/kaggle/input/ristek-datathon-2022/media/Image/EN-bQuFUEAEbNJx.jpg
/kaggle/input/ristek-datathon-2022/media/Image/EPX84CNU4AArur8.jpg
/kaggle/input/ristek-datathon-2022/media/Image/EOy-xGWU8AAPmN0.jpg
/kaggle/input/ristek-datathon-2022/media/Image/ENNgeB3UEAATPc5.jpg
/kaggle/input/ristek-datathon-2022/media/Image/ENLSSZiU8AEpGwD.jpg
/kaggle/input/ristek-datathon-2022/media/Image/ENkCNHpUwAAsY41.jpg
/kaggle/input/ristek-datathon-2022/media/Image/ENqggmFXsAEf9kr.jpg
/kaggle/input/ristek-datathon-2022/media/Image/EOCLobLU0AAk53w.jpg
/kaggle/input/ristek-datathon-2022/media/Image/EMNud-uVAAAZXPN.jpg
/kaggle/input/ristek-datathon-2022/media/Image/ENc5w_RUEAEbd9b.jpg
/kaggle/input/ristek-datathon-2022/media/Image/ENSrkNJVUAEBfOO.jpg
/kaggle/input/ristek-datathon-2022/media/Image/ENRrvB1VUAAoM9l.jpg
/kaggle/input/ristek-datathon-2022/media/Image/ENQAIJ5UcAAaV_Q.jpg
/kaggle/input/ristek-datathon-2022/media/Image/EPe5UJIUYAAaMmA.jpg
/kaggle/input/ristek-datathon-2022/media/Image/EOeA4R4UwAAPivI.jpg
/kaggle/input/ristek-datathon-2022/media/Image/EM4_Au8VAAArOna.jpg
/kaggle/input/ristek-datathon-2022/media/Image/ERlEtKFUYAAs8U3.jpg
/kaggle/input/ristek-datathon-2022/media/Image/ENP1qzhU0AAnTxL.jpg
/kaggle/input/ristek-datathon-2022/media/Image/ENMs3OmUwAAKUgn.jpg
/kaggle/input/ristek-datathon-2022/media/Image/EOWDwYoUYAERfXe.jpg
/kaggle/input/ristek-datathon-2022/media/Image/ERczYHqUcAAlPaE.jpg
/kaggle/input/ristek-datathon-2022/media/Image/EOVCPD6UcAAGaN-.jpg
/kaggle/input/ristek-datathon-2022/media/Image/ENJ8yqwUUAEOmuU.jpg
/kaggle/input/ristek-datathon-2022/media/Image/ENltcu5UYAAuhmO.jpg
/kaggle/input/ristek-datathon-2022/media/Image/ER1kBM2U4AAcuSC.jpg
/kaggle/input/ristek-datathon-2022/media/Image/ER1JKo4UUAEz11H.jpg
/kaggle/input/ristek-datathon-2022/media/Image/ENRv7SKU4AESdwZ.jpg
/kaggle/input/ristek-datathon-2022/media/Image/ENaZFkaVUAIQz2R.jpg
/kaggle/input/ristek-datathon-2022/media/Image/EUP0tlLUcAAkW2Y.jpg
/kaggle/input/ristek-datathon-2022/media/Image/ENqroCJUUAAUHiS.jpg
... (truncated) ...
/kaggle/input/ristek-datathon-2022/media/Image/ENQnOi_UwAAidXM.jpg
/kaggle/input/ristek-datathon-2022/media/Image/EOUu5ySUYAEr77h.jpg
/kaggle/input/ristek-datathon-2022/media/Image/EMIi0evUEAAbIrz.jpg
/kaggle/input/ristek-datathon-2022/media/Image/EOsmWMfU8AAj-iE.jpg
/kaggle/input/ristek-datathon-2022/media/Image/EPbgH7TUEAAXS0X.jpg
/kaggle/input/ristek-datathon-2022/media/Image/ENKJjftUwAAPOU3.jpg
/kaggle/input/ristek-datathon-2022/media/Image/ESi80VOUMAEMbfk.jpg
/kaggle/input/ristek-datathon-2022/media/Image/ELWgH2xUYAIQHoZ.jpg
/kaggle/input/ristek-datathon-2022/media/Image/ENJtA3sVUAATYlI.jpg
/kaggle/input/ristek-datathon-2022/media/Image/ENS4ytBUwAAdlAG.jpg
/kaggle/input/ristek-datathon-2022/media/Image/ENl9LRyU4AEaW0v.jpg
/kaggle/input/ristek-datathon-2022/media/Image/ELYnzQ6UYAAqSj5.jpg
/kaggle/input/ristek-datathon-2022/media/Image/ERlc9huWsAAJddh.jpg
/kaggle/input/ristek-datathon-2022/media/Image/EQONG39U0AEU_37.png
/kaggle/input/ristek-datathon-2022/media/Image/EPrlcT9VAAEQcfj.jpg
/kaggle/input/ristek-datathon-2022/media/Image/ERd3iSUUEAEJOK8.jpg
/kaggle/input/ristek-datathon-2022/media/Image/ENbkHHeUwAAmuX-.jpg
/kaggle/input/ristek-datathon-2022/media/Image/ENVumq3VUAIv8AK.jpg
/kaggle/input/ristek-datathon-2022/media/Image/EJ72cKXU4AAUU2u.jpg
/kaggle/input/ristek-datathon-2022/media/Image/EMdGzQhVUAARMHS.jpg
/kaggle/input/ristek-datathon-2022/media/Image/ENQseKlU8AAonMK.jpg
/kaggle/input/ristek-datathon-2022/media/Image/ENIBxfsUcAAGhn2.jpg
/kaggle/input/ristek-datathon-2022/media/Image/ENKyGb_UYAAuiY-.jpg
/kaggle/input/ristek-datathon-2022/media/Image/ENSGlSkU8AA90ze.jpg
/kaggle/input/ristek-datathon-2022/media/Image/ERk8RuTUEAA9EOn.jpg
/kaggle/input/ristek-datathon-2022/media/Image/ENNv6VEVUAAOvKI.jpg
/kaggle/input/ristek-datathon-2022/media/Image/ERZ9DHLU4AAxjlg.jpg
/kaggle/input/ristek-datathon-2022/media/Image/EMAcoFTUYAAVsf6.jpg
/kaggle/input/ristek-datathon-2022/media/Image/ENq54U1UUAAGocE.jpg
/kaggle/input/ristek-datathon-2022/media/Image/ERLvkWkUcAANPWD.jpg
/kaggle/input/ristek-datathon-2022/media/Image/ENUa_dgU4AEob15.jpg
/kaggle/input/ristek-datathon-2022/media/Image/EPYgZq5UUAA0YQT.jpg
/kaggle/input/ristek-datathon-2022/media/Image/ERqqS54U4AA8xY9.jpg
/kaggle/input/ristek-datathon-2022/media/Image/ENwA2QTUYAAQY9m.jpg
/kaggle/input/ristek-datathon-2022/media/Image/ENR-PqvUEAAp_NP.jpg
/kaggle/input/ristek-datathon-2022/media/Image/ENgNUbsU0AEx4I1.jpg
/kaggle/input/ristek-datathon-2022/media/Image/EOu92pYVUAEZpX9.jpg
/kaggle/input/ristek-datathon-2022/media/Image/ERb1FmaU0AA_-Kl.jpg
/kaggle/input/ristek-datathon-2022/media/Image/ENp595wU4AEms6c.jpg

In [2]:
import torch, torchvision
import matplotlib.pyplot as plt
import json
import cv2
import numpy as np
from copy import deepcopy
from glob import glob
import pandas as pd
import pickle
from sklearn.model_selection import train_test_split
import gc

/opt/conda/lib/python3.10/site-packages/requests/__init__.py:109: RequestsDependencyWarning: urllib3 (2.1.0) or chardet (None)/charset_normalizer (3.3.2) doesn't match a supported version!
  warnings.warn(

In [3]:
def process_image(df):
    images = []
    texts = []
    for index, row in df.iterrows():
        img = plt.imread(f'/kaggle/input/ristek-datathon-2022/media/{row["media"]}')

        #       # Detectron expects BGR images
        #       img_bgr = cv2.cvtColor(img, cv2.COLOR_RGB2BGR)
        images.append(img)

        text = row["text"]
        texts.append(text)
    return images, texts

In [4]:
def path_expander(row):
    img_dir = '/kaggle/input/ristek-datathon-2022/media/Image/' + row
    return img_dir

In [5]:
def stratified_sample_df(df, col, n_samples):
    sample_train, drop_train = train_test_split(df, train_size=n_samples, stratify=df["label"], shuffle=True, random_state=42)
    return sample_train, drop_train

In [6]:
train_df = pd.read_csv(f"/kaggle/input/ristek-datathon-2022/train.csv")
test_df = pd.read_csv(f"/kaggle/input/ristek-datathon-2022/test.csv")

train_df.head()

,created_at,id,user_id,user_name,url,text,media,label
0,2020-02-23 04:06:39+00:00,1231430140824973313,133931409,r0b1 sur1a (黄玉春),https://twitter.com/R0b1Sur1a/status/123143014...,Akhirnya sampai juga setelah menerobos banjir....,ERbrKgFU4AAnADb.jpg,0
1,2020-01-05 01:46:46+00:00,1213637932411580417,253063316,Beradaptasi di Era Pandemi ☀️,https://twitter.com/MarikaRahman_/status/12136...,"Kemekes RI, IDI Banten, IBI Banten dan PPNI Ba...",ENe1HUVUEAANLFT.jpg,0
2,2020-01-18 06:22:09+00:00,1218418277946396673,64318803,rywyu,https://twitter.com/rywyu/status/1218418277946...,Dikarenakan cikini rada2 banjir tdi pagi hingg...,EOiw80RU0AcJ4CI.jpg,0
3,2020-02-22 23:38:00+00:00,1231362534717837313,17383917,ICALIZERS,https://twitter.com/icalizers/status/123136253...,#sperma TT dikala warga jakarta sedang prihati...,ERatrt9UYAAtLMI.jpg,0
4,2019-12-17 10:54:31+00:00,1206890412574568449,3102973556,AN,https://twitter.com/lokbin103/status/120689041...,"KUIS!\n\nJakarta banjir parah hari ini, pertan...",EL-8Z-vUcAIiIlV.jpg,0

In [7]:
train_df['img_dir'] = train_df['media'].apply(path_expander)
test_df['img_dir'] = test_df['media'].apply(path_expander)

In [8]:
train_df = train_df[['img_dir','label','text']]
test_df = test_df[['img_dir','text']]

In [9]:
print(f"Before sample shape: {train_df.shape}")
train_df, val_df = stratified_sample_df(train_df, "label", 0.8)
print(f"After sample shape: {train_df.shape}")

Before sample shape: (1518, 3)
After sample shape: (1214, 3)

In [10]:
# from IPython.display import Image, display
# pil_img = Image(filename='/kaggle/input/ristek-datathon-2022/media/Image/'+train_df.iloc[0]['media'])
# display(pil_img)

In [11]:
pip install --upgrade pip

In [12]:
pip install autogluon

In [13]:
pip install boto3 --upgrade

In [14]:
from autogluon.multimodal import MultiModalPredictor

predictor = MultiModalPredictor(label='label', problem_type='binary',eval_metric='f1',validation_metric='f1')
predictor.fit(
    train_data=train_df,
    tuning_data=val_df,
    hyperparameters={"optimization.learning_rate": 1e-5,'optimization.patience':3, "model.hf_text.checkpoint_name": "indolem/indobertweet-base-uncased"}
)

GPU Count: 1
GPU Count to be Used: 1
GPU 0 Name: Tesla P100-PCIE-16GB
GPU 0 Memory: 0.11GB/16.0GB (Used/Total)

INFO: Using 16bit Automatic Mixed Precision (AMP)
INFO: GPU available: True (cuda), used: True
INFO: TPU available: False, using: 0 TPU cores
INFO: IPU available: False, using: 0 IPUs
INFO: HPU available: False, using: 0 HPUs
INFO: LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
INFO:
  | Name              | Type                | Params
----------------------------------------------------------
0 | model             | MultimodalFusionMLP | 207 M
1 | validation_metric | BinaryF1Score       | 0
2 | loss_func         | CrossEntropyLoss    | 0
----------------------------------------------------------
207 M     Trainable params
0         Non-trainable params
207 M     Total params
830.511   Total estimated model params size (MB)

INFO: Epoch 0, global step 4: 'val_f1' reached 0.15556 (best 0.15556), saving model to '/kaggle/working/AutogluonModels/ag-20240419_162801/epoch=0-step=4.ckpt' as top 3

INFO: Epoch 0, global step 10: 'val_f1' reached 0.20690 (best 0.20690), saving model to '/kaggle/working/AutogluonModels/ag-20240419_162801/epoch=0-step=10.ckpt' as top 3

INFO: Epoch 1, global step 14: 'val_f1' reached 0.50000 (best 0.50000), saving model to '/kaggle/working/AutogluonModels/ag-20240419_162801/epoch=1-step=14.ckpt' as top 3

INFO: Epoch 1, global step 20: 'val_f1' reached 0.59130 (best 0.59130), saving model to '/kaggle/working/AutogluonModels/ag-20240419_162801/epoch=1-step=20.ckpt' as top 3

INFO: Epoch 2, global step 24: 'val_f1' reached 0.60656 (best 0.60656), saving model to '/kaggle/working/AutogluonModels/ag-20240419_162801/epoch=2-step=24.ckpt' as top 3

INFO: Epoch 2, global step 30: 'val_f1' reached 0.62903 (best 0.62903), saving model to '/kaggle/working/AutogluonModels/ag-20240419_162801/epoch=2-step=30.ckpt' as top 3

INFO: Epoch 3, global step 34: 'val_f1' reached 0.65116 (best 0.65116), saving model to '/kaggle/working/AutogluonModels/ag-20240419_162801/epoch=3-step=34.ckpt' as top 3

INFO: Epoch 3, global step 40: 'val_f1' reached 0.64567 (best 0.65116), saving model to '/kaggle/working/AutogluonModels/ag-20240419_162801/epoch=3-step=40.ckpt' as top 3

INFO: Epoch 4, global step 44: 'val_f1' reached 0.66667 (best 0.66667), saving model to '/kaggle/working/AutogluonModels/ag-20240419_162801/epoch=4-step=44.ckpt' as top 3

INFO: Epoch 4, global step 50: 'val_f1' reached 0.69118 (best 0.69118), saving model to '/kaggle/working/AutogluonModels/ag-20240419_162801/epoch=4-step=50.ckpt' as top 3

INFO: Epoch 5, global step 54: 'val_f1' reached 0.69118 (best 0.69118), saving model to '/kaggle/working/AutogluonModels/ag-20240419_162801/epoch=5-step=54.ckpt' as top 3

INFO: Epoch 5, global step 60: 'val_f1' reached 0.68148 (best 0.69118), saving model to '/kaggle/working/AutogluonModels/ag-20240419_162801/epoch=5-step=60.ckpt' as top 3
Start to fuse 3 checkpoints via the greedy soup algorithm.

AutoMM has created your model. 🎉🎉🎉

To load the model, use the code below:
    ```python
    from autogluon.multimodal import MultiModalPredictor
    predictor = MultiModalPredictor.load("/kaggle/working/AutogluonModels/ag-20240419_162801")
    ```

If you are not satisfied with the model, try to increase the training time,
adjust the hyperparameters (https://auto.gluon.ai/stable/tutorials/multimodal/advanced_topics/customization.html),
or post issues on GitHub (https://github.com/autogluon/autogluon/issues).

In [15]:
predictor = MultiModalPredictor.load('/kaggle/working/AutogluonModels/ag-20240419_152051/epoch=3-step=34.ckpt')

AssertionError: '/kaggle/working/AutogluonModels/ag-20240419_152051/epoch=3-step=34.ckpt' must be an existing directory.

In [16]:
result = predictor.predict(test_df)

In [17]:
result.value_counts()

label
0    785
1    226
Name: count, dtype: int64

In [18]:
submission = pd.read_csv('/kaggle/input/ristek-datathon-2022/sample_submission.csv')

In [19]:
submission.head()

                    id  label
0  1213309429254250496      0
1  1216196702647939072      0
2  1216296533735309312      0
3  1234385081482956800      0
4  1214853229567041537      0

In [20]:
submission['label'] = result

In [21]:
submission.to_csv('autogluon3.csv', index=False)