# Zero-shot tweet topic labelling with GPT-4o through LangChain

In [ ]:
DATA_DIR = "../data"

In [20]:
import os
from langchain.memory import ConversationBufferMemory
from langchain.chains import ConversationChain
from langchain.prompts import ChatPromptTemplate
from langchain_openai import OpenAI, ChatOpenAI

import pandas as pd
from sklearn.model_selection import train_test_split
from tqdm import tqdm

In [5]:
chat = ChatOpenAI(
    openai_api_key=os.environ["OPENAI_API_KEY"],
    temperature=0,
    streaming=True,
    # callbacks=[StreamingStdOutCallbackHandler()],
    model_name="gpt-4o",
)

In [6]:
chat.model_name

'gpt-4o'

## Example

In [7]:
chat_template = ChatPromptTemplate.from_template("""
Diberikan sebuah tweet, anda harus mengklasifikasikan apakah tweet ini termasuk kategori apa? Pilih salah satu kategori diantara 8 kategori berikut:
1. Politik
2. Sosial Budaya
3. Ekonomi
4. Pertahanan dan Keamanan
5. Ideologi
6. Sumber Daya Alam
7. Demografi
8. Geografi

tweet:
{text}

label?

cukup jawab dengan nama kategorinya tidak perlu menjawab apa-apa lagi.
contoh jawaban: "Kategori"
""")

In [8]:
memory = ConversationBufferMemory()
conversation = ConversationChain(
    llm=chat,
    memory = memory,
    verbose=True
)

In [42]:
ex1 = chat_template.format_messages(text="Kunjungan Prabowo ini untuk meresmikan dan menyerahkan proyek bantuan air bersih di lima titik. #IndonesiaSentris #IndonesiaHijau #02Melanjutkan #AnakMudaIndonesiaEmas Prabowo Subianto")

In [43]:
conversation.predict(input=ex1)

> Entering new ConversationChain chain...
Prompt after formatting:
The following is a friendly conversation between a human and an AI. The AI is talkative and provides lots of specific details from its context. If the AI does not know the answer to a question, it truthfully says it does not know.

Current conversation:

Human: [HumanMessage(content='\nDiberikan sebuah tweet, anda harus mengklasifikasikan apakah tweet ini termasuk kategori apa? Pilih salah satu kategori diantara 8 kategori berikut:\n1. Politik\n2. Sosial Budaya\n3. Ekonomi\n4. Pertahanan dan Keamanan\n5. Ideologi\n6. Sumber Daya Alam\n7. Demografi\n8. Geografi\n\ntweet:\nKunjungan Prabowo ini untuk meresmikan dan menyerahkan proyek bantuan air bersih di lima titik. #IndonesiaSentris #IndonesiaHijau #02Melanjutkan #AnakMudaIndonesiaEmas Prabowo Subianto\n\nlabel?\n\ncukup jawab dengan nama kategorinya tidak perlu menjawab apa-apa lagi.\ncontoh jawaban: "Kategori"\n')]
AI:

> Finished chain.

'Sosial Budaya'

In [44]:
conversation.predict(input="RT Mas Ganjar bawa data dan ngasih pertanyaan berdasar data. Bisa saja dijawab oleh Pak Prabowo tanpa bilang data dari Mas Ganjar salah. Tapi karena Pak Prabowo bilang datanya salah, wajar jika Mas Ganjar minta ditunjukkan mana data yang benar. Gak ada urusan sama waktu yang singkat. [RE pangeransiahaan]")

> Entering new ConversationChain chain...
Prompt after formatting:
The following is a friendly conversation between a human and an AI. The AI is talkative and provides lots of specific details from its context. If the AI does not know the answer to a question, it truthfully says it does not know.

Current conversation:
Human: [{'content': '\nDiberikan sebuah tweet, anda harus mengklasifikasikan apakah tweet ini termasuk kategori apa? Pilih salah satu kategori diantara 8 kategori berikut:\n1. Politik\n2. Sosial Budaya\n3. Ekonomi\n4. Pertahanan dan Keamanan\n5. Ideologi\n6. Sumber Daya Alam\n7. Demografi\n8. Geografi\n\ntweet:\nKunjungan Prabowo ini untuk meresmikan dan menyerahkan proyek bantuan air bersih di lima titik. #IndonesiaSentris #IndonesiaHijau #02Melanjutkan #AnakMudaIndonesiaEmas Prabowo Subianto\n\nlabel?\n\ncukup jawab dengan nama kategorinya tidak perlu menjawab apa-apa lagi.\ncontoh jawaban: "Kategori"\n', 'additional_kwargs': {}, 'response_metadata': {}, 'type': 'human', 'name': None, 'id': None, 'example': False}]
AI: Sosial Budaya
Human: RT Mas Ganjar bawa data dan ngasih pertanyaan berdasar data. Bisa saja dijawab oleh Pak Prabowo tanpa bilang data dari Mas Ganjar salah. Tapi karena Pak Prabowo bilang datanya salah, wajar jika Mas Ganjar minta ditunjukkan mana data yang benar. Gak ada urusan sama waktu yang singkat. [RE pangeransiahaan]
AI:

> Finished chain.

'Politik'

In [45]:
conversation.predict(input="RT @BUMlUyYYGIARoOH2Nx/iuCAFpXprUov+NM3cvB2DtYI= Wait wait pak. Ada bukti pak anies gunakan politik identitas ? Bukankah justru ahok yang terang terangan. Bahkan sebelum pilkada saja sudah memantik perselisihan misal gunakan password wifi dengan kata ""kafir"". Berpikir adil itu memang sulit pak. https://t.co/tCzvhvR2G9 [RE iahk25]")

> Entering new ConversationChain chain...
Prompt after formatting:
The following is a friendly conversation between a human and an AI. The AI is talkative and provides lots of specific details from its context. If the AI does not know the answer to a question, it truthfully says it does not know.

Current conversation:
Human: [{'content': '\nDiberikan sebuah tweet, anda harus mengklasifikasikan apakah tweet ini termasuk kategori apa? Pilih salah satu kategori diantara 8 kategori berikut:\n1. Politik\n2. Sosial Budaya\n3. Ekonomi\n4. Pertahanan dan Keamanan\n5. Ideologi\n6. Sumber Daya Alam\n7. Demografi\n8. Geografi\n\ntweet:\nKunjungan Prabowo ini untuk meresmikan dan menyerahkan proyek bantuan air bersih di lima titik. #IndonesiaSentris #IndonesiaHijau #02Melanjutkan #AnakMudaIndonesiaEmas Prabowo Subianto\n\nlabel?\n\ncukup jawab dengan nama kategorinya tidak perlu menjawab apa-apa lagi.\ncontoh jawaban: "Kategori"\n', 'additional_kwargs': {}, 'response_metadata': {}, 'type': 'human', 'name': None, 'id': None, 'example': False}]
AI: Sosial Budaya
Human: RT Mas Ganjar bawa data dan ngasih pertanyaan berdasar data. Bisa saja dijawab oleh Pak Prabowo tanpa bilang data dari Mas Ganjar salah. Tapi karena Pak Prabowo bilang datanya salah, wajar jika Mas Ganjar minta ditunjukkan mana data yang benar. Gak ada urusan sama waktu yang singkat. [RE pangeransiahaan]
AI: Politik
Human: RT @BUMlUyYYGIARoOH2Nx/iuCAFpXprUov+NM3cvB2DtYI= Wait wait pak. Ada bukti pak anies gunakan politik identitas ? Bukankah justru ahok yang terang terangan. Bahkan sebelum pilkada saja sudah memantik perselisihan misal gunakan password wifi dengan kata kafir. Berpikir adil itu memang sulit pak. https://t.co/tCzvhvR2G9 [RE iahk25]
AI:

> Finished chain.

'Politik'

In [46]:
conversation.predict(input="RT According to Prabowo, Gaza is opressed because they don't have a sufficient military power. This is such a tone-deaf statement coming from a Minister of Defense. [RE WAPamungkas]")

> Entering new ConversationChain chain...
Prompt after formatting:
The following is a friendly conversation between a human and an AI. The AI is talkative and provides lots of specific details from its context. If the AI does not know the answer to a question, it truthfully says it does not know.

Current conversation:
Human: [{'content': '\nDiberikan sebuah tweet, anda harus mengklasifikasikan apakah tweet ini termasuk kategori apa? Pilih salah satu kategori diantara 8 kategori berikut:\n1. Politik\n2. Sosial Budaya\n3. Ekonomi\n4. Pertahanan dan Keamanan\n5. Ideologi\n6. Sumber Daya Alam\n7. Demografi\n8. Geografi\n\ntweet:\nKunjungan Prabowo ini untuk meresmikan dan menyerahkan proyek bantuan air bersih di lima titik. #IndonesiaSentris #IndonesiaHijau #02Melanjutkan #AnakMudaIndonesiaEmas Prabowo Subianto\n\nlabel?\n\ncukup jawab dengan nama kategorinya tidak perlu menjawab apa-apa lagi.\ncontoh jawaban: "Kategori"\n', 'additional_kwargs': {}, 'response_metadata': {}, 'type': 'human', 'name': None, 'id': None, 'example': False}]
AI: Sosial Budaya
Human: RT Mas Ganjar bawa data dan ngasih pertanyaan berdasar data. Bisa saja dijawab oleh Pak Prabowo tanpa bilang data dari Mas Ganjar salah. Tapi karena Pak Prabowo bilang datanya salah, wajar jika Mas Ganjar minta ditunjukkan mana data yang benar. Gak ada urusan sama waktu yang singkat. [RE pangeransiahaan]
AI: Politik
Human: RT @BUMlUyYYGIARoOH2Nx/iuCAFpXprUov+NM3cvB2DtYI= Wait wait pak. Ada bukti pak anies gunakan politik identitas ? Bukankah justru ahok yang terang terangan. Bahkan sebelum pilkada saja sudah memantik perselisihan misal gunakan password wifi dengan kata kafir. Berpikir adil itu memang sulit pak. https://t.co/tCzvhvR2G9 [RE iahk25]
AI: Politik
Human: RT According to Prabowo, Gaza is opressed because they don't have a sufficient military power. This is such a tone-deaf statement coming from a Minister of Defense. [RE WAPamungkas]
AI:

> Finished chain.

'Pertahanan dan Keamanan'

## Real Deal

In [9]:
train_df = pd.read_csv(f'{DATA_DIR}/train.csv', sep=";")
train_df.head()

                                                text             label
0  Kunjungan Prabowo ini untuk meresmikan dan men...  Sumber Daya Alam
1  RT Anies dapat tepuk tangan meriah saat jadi R...           Politik
2  @CIqXqwGAT04tMtx4OCATxjoVq7vv/Y8HeYaIOgMFg8Y= ...         Demografi
3  RT @L3R8XFBw3WGbxRPSj0/0hHZTbqVGX7qtfwRg9zmhK7...           Politik
4  Anies Baswedan Harap ASN termasuk TNI dan Polr...           Politik

In [10]:
train_df.shape

(5000, 2)

In [11]:
def drop_duplicated(df):
    print("Df size:", train_df.shape)
    train_df.drop_duplicates(subset=['text', 'label'], keep='first', inplace=True)
    print("After dropping literal duplicated rows, df size: ", train_df.shape)
    train_df.drop_duplicates(subset=['text'], keep=False, inplace=True)
    print("After dropping text duplicated rows, df size: ", train_df.shape)
    
drop_duplicated(train_df)

Df size: (5000, 2)
After dropping literal duplicated rows, df size:  (4619, 2)
After dropping text duplicated rows, df size:  (4547, 2)

In [12]:
train_df, val_df = train_test_split(train_df, train_size=0.2, stratify=train_df.label, random_state=42)
train_df.shape

(909, 2)

In [13]:
train_df.label.value_counts()

label
Politik                    588
Sosial Budaya               82
Ideologi                    67
Pertahanan dan Keamanan     65
Ekonomi                     61
Sumber Daya Alam            30
Demografi                   12
Geografi                     4
Name: count, dtype: int64

In [14]:
# drop randomly 70% of the data that has label = Politik
train_df = train_df.drop(train_df[train_df.label == "Politik"].sample(frac=0.9, random_state=42).index)
train_df.label.value_counts()

label
Sosial Budaya              82
Ideologi                   67
Pertahanan dan Keamanan    65
Ekonomi                    61
Politik                    59
Sumber Daya Alam           30
Demografi                  12
Geografi                    4
Name: count, dtype: int64

In [15]:
train_df.shape

(380, 2)

In [22]:
memory = ConversationBufferMemory()
conversation = ConversationChain(
    llm=chat,
    memory = memory,
    verbose=False
)

for i, (idx, row) in tqdm(enumerate(train_df.iterrows())):
    if i == 0:
        inp = chat_template.format_messages(text=row.text)
        res = conversation.predict(input=inp)
    else:
        res = conversation.predict(input=row.text)
    train_df.loc[idx, 'predicted_label'] = str(res)
    train_df.to_csv(f'{DATA_DIR}/train_lc.csv', index=False)
train_df.head()

RateLimitError: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

In [23]:
train_lc = pd.read_csv(f'{DATA_DIR}/train_lc.csv')
train_lc.dropna(subset=['predicted_label'], inplace=True)
train_lc.shape

(138, 3)

In [24]:
train_lc.head()

,text,label,predicted_label
0,RT Ã°ÂÂ—Â™Ã°ÂÂ—Â”Ã°ÂÂ—Â§Ã°ÂÂ—Â”Ã°ÂÂ— Ã°Â...,Ideologi,Politik
1,RT Foto ini saya ambil tgl 21 Mei 2019 - bbrp ...,Politik,Pertahanan dan Keamanan
2,RT @ts4EqrqE3f1Gb/sq1rSAV9TEKUX2QNPQO7x9LLq9Ts...,Pertahanan dan Keamanan,Pertahanan dan Keamanan
3,kalau mau melihat Indonesia yg asli. Indonesia...,Ideologi,Sosial Budaya
4,Masyarakat Dander Bojonegoro Bahagia Untuk mem...,Sosial Budaya,Politik

In [25]:
from sklearn.metrics import classification_report

print(classification_report(train_lc.label, train_lc.predicted_label))

                         precision    recall  f1-score   support

              Demografi       0.50      0.40      0.44         5
                Ekonomi       0.63      0.86      0.73        22
               Geografi       0.00      0.00      0.00         0
               Ideologi       1.00      0.26      0.41        23
Pertahanan dan Keamanan       0.77      0.65      0.71        26
                Politik       0.26      0.30      0.28        20
          Sosial Budaya       0.55      0.81      0.66        32
       Sumber Daya Alam       0.60      0.30      0.40        10

               accuracy                           0.57       138
              macro avg       0.54      0.45      0.45       138
           weighted avg       0.64      0.57      0.56       138

d:\miniconda3\envs\tf\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
d:\miniconda3\envs\tf\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
d:\miniconda3\envs\tf\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))