# Text cleaning, hashtag normalisation, English translation and a CatBoost text model

In [ ]:
DATA_DIR = "../data"

In [ ]:
import pandas as pd
import numpy as np
import re

from transformers import (
    AutoTokenizer,
    TrainingArguments,
    Trainer,
    AutoModelForSequenceClassification,
    EarlyStoppingCallback
)


from catboost import CatBoostClassifier, Pool

from sklearn.model_selection import train_test_split, cross_val_score, RepeatedStratifiedKFold
from sklearn.metrics import classification_report, accuracy_score, recall_score, precision_score, \
    balanced_accuracy_score
from datasets import Dataset, DatasetDict

In [ ]:
def remove_noise(text):
    text = str(text)
    # remove mentions
    text = re.sub(r'@[\S+]+', '', text)
    # remove hashtags
    # text = re.sub(r'#\w+', '', text)
    # remove RT
    text = re.sub(r'RT[\s]+', '', text)
    # remove [RE ...]
    text = re.sub(r'\[RE [^\]]*\]', '', text)
    # remove urls
    text = re.sub(r'https?:\/\/\S+', '', text)
    # remove emojis
    text = re.sub(r'[^\x00-\x7F]+', ' ', text)
    # fix &amp;
    text = re.sub(r'&amp;', 'dan', text)
    # fix w/
    text = re.sub(r'w/', 'with', text)
    # fix 3
    text = re.sub(r'(?<=\w)3(?=\w)', 'e', text)
    # remove any non alphanumeric characters
    text = re.sub(r'[^A-Za-z0-9 ]', ' ', text)
    # fix unspaced words
    new_text = []
    for word in text.split():
        # weird word
        if word in ["BEiqnH5xQr", "JN18A"]:
            continue
        # fix shorten names
        elif word == "JK":
            new_text.append("jusuf kalla")
        elif word.lower() == "jkw":
            new_text.append("jokowi")
        elif word.lower() in ["bowo", "ayahbowo"]:
            new_text.append("prabowo")
        elif word.lower() in ["ayahbowogbran", "pbowogbran", "masbowogbran"]:
            new_text.append("pabrowo gibran")
        elif word == "MasGBRAN":
            new_text.append("gibran")
        elif word == "SBY":
            new_text.append("susilo bambang yudhoyono")
        elif word == "AHY":
            new_text.append("agnes haryani")
        # keep as is
        elif re.fullmatch(r'[A-Z]+', word) or word.lower() in ["s1", "s2", "s3"]:
            new_text.append(word)
        else:
            # fix unspaced words
            new_text.append(re.sub(r'(?<=[a-z])(?=[A-Z])|(?<=[A-Za-z])(?=[0-9])|(?<=[0-9])(?=[A-Za-z])|(?<=[A-Z])(?=[A-Z][a-z])', ' ', word))
    text = ' '.join(new_text)
    # remove extra spaces
    text = re.sub(r'\s+', ' ', text)
    # remove whitespace leading & trailing
    text = text.strip()
    return text

def normalize_word(text):
    map = {
        "sj": "saja",
        "yg": "yang",
        "dgn": "dengan",
        "dg": "dengan",
        "dpt": "dapat",
        "dptkan": "dapatkan",
        "hnya": "hanya",
        "skrng": "sekarang",
        "uu": "undang undang",
        "asn": "aparatur sipil negara",
        "ordal": "orang dalam",
        "mrk": "mereka",
        "rmh": "rumah",
        "kpk": "komisi pemberantasan korupsi",
        "blg": "bilang",
        "tuch": "tuh",
        "umkm": "usaha mikro kecil menengah",
        "jis": "jakarta international stadium",
        "jkt": "jakarta",
        "spt": "seperti",
        "tps": "tempat pemungutan suara",
        "alkes": "alat kesehatan",
        "bowo": "prabowo",
    }

    text = text.replace("UU ITE", "Undang Undang Informasi dan Transaksi Elektronik")
    text = text.replace("kitamasbowo dangbran", "kita pilih prabowo dan gibran")
    text = text.replace("PDI P", "PDIP")
    text = text.replace("PDI Perjuangan", "PDIP")

    party_names = [
        "pkb",
        "gerindra",
        "pdi",
        "pdip",
        "golkar",
        "nasdem",
        "gelora",
        "pks",
        "pkn",
        "hanura",
        "pan",
        "pbb",
        "demokrat",
        "psi",
        "perindo",
        "ppp",
        "ummat",
        "pna",
        "gabthat",
        "pda",
        "sira"
    ]

    stop_words = [
        "dekade08",
        "tempodotco",
        "md"
    ]

    new_text = []
    for word in text.split():
        if word.lower() in map:
            new_text.append(map[word.lower()])
        elif word.lower() in party_names:
            new_text.append("Partai Politik")
        elif word.lower() in stop_words:
            continue
        else:
            new_text.append(word)

    text = ' '.join(new_text)
    return text

def drop_duplicated(df):
    print("Df size:", df.shape)
    df.drop(df[df['text'].str.len() == 0].index, inplace=True)
    print("After dropping empty text rows, df size: ", df.shape)
    df.drop_duplicates(subset=['text', 'label'], keep='first', inplace=True)
    print("After dropping literal duplicated rows, df size: ", df.shape)
    df.drop_duplicates(subset=['text'], keep=False, inplace=True)
    print("After dropping text duplicated rows, df size: ", df.shape)
    return df

In [ ]:
train_df = pd.read_csv(f"{DATA_DIR}/train.csv")

train_df['text'] = train_df['text'].apply(remove_noise)
train_df['text'] = train_df['text'].apply(normalize_word)
train_df = drop_duplicated(train_df)
train_df.head()

Df size: (4583, 3)
After dropping empty text rows, df size:  (4574, 3)
After dropping literal duplicated rows, df size:  (4297, 3)
After dropping text duplicated rows, df size:  (4252, 3)

                                                text     label  label_cnt
0  Jangan Golput pilih Capres No 3 Ganjar Pranowo...  Geografi         20
2  Itu juga pulau yang jalan krna emg udah jadi d...  Geografi         20
3  Jadi mau pindah nanti ke IKN kalo dapet rezeki...  Geografi         20
4  kampung ku di aeange deket bukit tinggi kamoun...  Geografi         20
5  Umat Islam rata rata mendukung Anies Baswedan ...  Geografi         20

In [ ]:
def translate_hashtags_in_dataframe(df, column_name):
    translation_map = {
        "#JNK": "#JNK",
        "#GanjarMahfudRebound": "#GanjarMahfudRebound",
        "#GanjarMahfud2024": "#GanjarMahfud2024",
        "#Coblos3": "#Vote3",
        "#02Melanjutkan": "#Continue02",
        "#AMINAjaDulu": "#JustAMINAFirst",
        "#L3bihbaik": "#Better3",
        "#3GM": "#3GM",
        "#IndonesiaSentris": "#IndonesiaCentric",
        "#IndonesiaHijau": "#GreenIndonesia",
        "#Ganjar": "#Ganjar",
        "#MahfudLebihBaik3": "#MahfudBetter3",
        "#DebatCapres": "#PresidentialDebate",
        "#AniesMuhaimin2024": "#AniesMuhaimin2024",
        "#TempoNasional": "#TempoNational",
        "#TabrakProf": "#HitTheProf",
        "#AsalBukanPrabowo": "#AnyoneButPrabowo",
        "#JabarTetapUntuk02": "#WestJavaStillFor02",
        "#SahabatGanjar": "#GanjarFriends",
        "#RembuGanjar": "#GanjarMeeting",
        "#02UntukMelanjutkan": "#02ToContinue",
        "#GanjarPresiden": "#GanjarPresident",
        "#DesakAnies": "#UrgeAnies",
        "#GanjarUntukSemua": "#GanjarForAll",
        "#GanjarMahfudM3nang": "#GanjarMahfudWin3",
        "#3MandatGanjarMahfud": "#3MandatesGanjarMahfud",
        "#PrabowoGemoy": "#CutePrabowo",
        "#JabarTetapPakBowo": "#WestJavaStillForBowo",
        "#PDIPerjuangan": "#PDIPerjuangan",
        "#Pilpres2024": "#PresidentialElection2024",
        "#MenataMasaDepan": "#ShapingTheFuture",
        "#news": "#news",
        "#GanjarPranowo": "#GanjarPranowo",
        "#MEnangkanGAnjar": "#WinGanjar",
        "#MenangSeputaran": "#WinningAround",
        "#update": "#update",
        "#kodekita08": "#codeour08",
        "#TemanAlamGanjar": "#GanjarNatureFriends",
        "#text": "#text",
        "#SatSetLebihBaik": "#BetterQuick",
        "#KratonBersamaRakyat": "#PalaceWithPeople",
        "#Pemilu2024": "#Election2024",
        "#nazarpemilu": "#ElectionVow",
        "#HardNews": "#HardNews",
        "#CariBeritaditvOne": "#FindNewsAtTvOne",
        "#AniesBaswedan": "#AniesBaswedan",
        "#Politik": "#Politics",
        "#tvOneTVPemilu": "#tvOneElectionTV",
        "#MauMemilih": "#WantToVote",
        "#Nomor3Pilihanku": "#MyChoiceIsNumber3",
        "#M3nangDebat4": "#WinDebate4",
        "#SatSet": "#Quick",
        "#PastiLebihBaik": "#DefinitelyBetter",
        "#aniesbaswedan": "#aniesbaswedan",
        "#newsupdate": "#newsupdate",
        "#prabowo": "#prabowo",
        "#GanjarSatSet": "#GanjarQuick",
        "#MahfudTasTes": "#MahfudTasTest",
        "#AniesPresiden2024": "#AniesPresident2024",
        "#GanjarMahfud": "#GanjarMahfud",
        "#JelasSama02": "#ClearWith02",
        "#Capres": "#PresidentialCandidate",
        "#pemilu2024": "#election2024",
        "#AtikohIbuNegara": "#AtikohFirstLady",
        "#NewsOne": "#NewsOne",
        "#Cawapres": "#VicePresidentialCandidate",
        "#Mahfud": "#Mahfud",
        "#HaveAniesDay": "#HaveAniesDay",
        "#TempoBisnis": "#TempoBusiness",
        "#PresidenRakyat": "#People'sPresident",
        "#DialogGanjar": "#GanjarDialogue",
        "#Prabowo": "#Prabowo",
        "#arsjadrasjid": "#arsjadrasjid",
        "#PersatuanNasional": "#NationalUnity",
    }

    def translate_text(text):
        words = text.split()
        translated_words = [translation_map.get(word, word) for word in words]
        return ' '.join(translated_words)

    df[column_name] = df[column_name].apply(translate_text)
    return df

train_df = translate_hashtags_in_dataframe(train_df, 'text')

In [ ]:
# reset index of df
train_df.reset_index(drop=True, inplace=True)

In [ ]:
from deep_translator import GoogleTranslator

def translate_to_en(text):
    return GoogleTranslator(source='auto', target='en').translate(text)

train_df['clean_text_en'] = train_df['text'].apply(translate_to_en)

In [ ]:
train_df.to_csv(f"{DATA_DIR}/train_cleaned_en_akmal.csv", index=False)

In [ ]:
train_df

                                                   text     label  label_cnt
0     Jangan Golput pilih Capres No 3 Ganjar Pranowo...  Geografi         20
1     Itu juga pulau yang jalan krna emg udah jadi d...  Geografi         20
2     Jadi mau pindah nanti ke IKN kalo dapet rezeki...  Geografi         20
3     kampung ku di aeange deket bukit tinggi kamoun...  Geografi         20
4     Umat Islam rata rata mendukung Anies Baswedan ...  Geografi         20
...                                                 ...       ...        ...
4247  Anies apresiasi jasa pendidik dengan bebaskan ...   Politik       2972
4248  Anies Bansos Diberikan Ikut Kalender Kebutuhan...   Politik       2972
4249  Anies nothing to lose harus total war targetny...   Politik       2972
4250  Closing Statement pak Anies di acara KADIN sem...   Politik       2972
4251  Capres nomor urut 3 Ganjar Pranowo menanggapi ...   Politik       2972

[4252 rows x 3 columns]

In [ ]:
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.feature_extraction import text
import umap.umap_ as umap



# Define custom stopwords
stop_words = list(text.ENGLISH_STOP_WORDS)

# Create TF-IDF Vectorizer with stopword removal
vectorizer = TfidfVectorizer(max_features=1000, stop_words=stop_words)
tfidf_matrix = vectorizer.fit_transform(train_df['text'])

# Convert the TF-IDF matrix to a DataFrame
tfidf_df = pd.DataFrame(tfidf_matrix.toarray(), columns=vectorizer.get_feature_names_out())

# Perform UMAP dimensionality reduction to 50 dimensions
reducer = umap.UMAP(n_components=50, random_state=42)
umap_features = reducer.fit_transform(tfidf_df)

# Convert the reduced features to a DataFrame for better visualization
umap_df = pd.DataFrame(umap_features, columns=[f"UMAP_{i}" for i in range(50)])

# Add the UMAP features to the original DataFrame
for i in range(50):
    train_df[f'UMAP_{i}'] = umap_df[f'UMAP_{i}']

/home/ikhlasul.hanif/miniconda3/envs/satdat/lib/python3.9/site-packages/umap/umap_.py:1945: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(f"n_jobs value {self.n_jobs} overridden to 1 by setting random_state. Use no seed for parallelism.")
/home/ikhlasul.hanif/miniconda3/envs/satdat/lib/python3.9/site-packages/numba/np/ufunc/parallel.py:371: NumbaWarning: The TBB threading layer requires TBB version 2021 update 6 or later i.e., TBB_INTERFACE_VERSION >= 12060. Found TBB_INTERFACE_VERSION = 12050. The TBB threading layer is disabled.
  warnings.warn(problem)

In [ ]:
train_df

                                                   text     label  label_cnt  \
0     Jangan Golput pilih Capres No 3 Ganjar Pranowo...  Geografi         20
1     Itu juga pulau yang jalan krna emg udah jadi d...  Geografi         20
2     Jadi mau pindah nanti ke IKN kalo dapet rezeki...  Geografi         20
3     kampung ku di aeange deket bukit tinggi kamoun...  Geografi         20
4     Umat Islam rata rata mendukung Anies Baswedan ...  Geografi         20
...                                                 ...       ...        ...
4247  Anies apresiasi jasa pendidik dengan bebaskan ...   Politik       2972
4248  Anies Bansos Diberikan Ikut Kalender Kebutuhan...   Politik       2972
4249  Anies nothing to lose harus total war targetny...   Politik       2972
4250  Closing Statement pak Anies di acara KADIN sem...   Politik       2972
4251  Capres nomor urut 3 Ganjar Pranowo menanggapi ...   Politik       2972

         UMAP_0     UMAP_1    UMAP_2    UMAP_3    UMAP_4    UMAP_5    UMAP_6  \
0      9.819674   9.878110  0.566112  5.639553  8.385981  2.485025  5.110412
1     10.393359   9.641378 -0.540884  7.368968  7.666936  2.776530  4.475051
2     10.110911   9.951305 -0.289725  7.166046  7.666677  3.239197  4.343348
3     10.084725   9.796647 -0.097422  6.852065  7.782521  2.636757  4.502750
4     10.276983   9.824596  0.070523  7.593552  7.432806  3.542999  4.582121
...         ...        ...       ...       ...       ...       ...       ...
4247  10.387262   9.814626 -0.592902  6.588658  7.837945  3.072002  4.253153
4248   9.985639  10.182143  0.331997  8.548603  7.233951  3.487427  4.487564
4249  10.184848   9.893972 -0.324297  7.296128  7.709228  2.882507  4.627234
4250  10.255561   9.697439  0.187231  7.165528  7.542428  3.648569  4.483389
4251   9.867221   9.735977  0.346649  6.276313  8.266153  2.490643  4.940298

      ...   UMAP_40   UMAP_41   UMAP_42   UMAP_43   UMAP_44   UMAP_45  \
0     ...  5.206729  5.580546  4.142110  4.391897  4.913282  4.656327
1     ...  5.492215  5.545050  4.097614  5.116201  5.235869  4.321980
2     ...  5.572574  5.225601  4.198992  4.757513  4.971737  4.448276
3     ...  5.534039  5.142920  4.238047  5.143494  5.426247  4.343235
4     ...  5.727096  5.055336  4.327113  5.072587  5.287614  4.451987
...   ...       ...       ...       ...       ...       ...       ...
4247  ...  5.298098  5.211567  4.310747  4.916460  5.132716  4.401878
4248  ...  5.908797  5.259470  4.191670  4.736769  4.890192  4.559519
4249  ...  5.670415  5.492138  4.054288  4.922271  5.117767  4.422387
4250  ...  5.756721  5.083270  4.382019  5.115443  5.356683  4.493793
4251  ...  5.274796  5.843657  4.033881  4.585065  4.907177  4.654047

       UMAP_46   UMAP_47   UMAP_48   UMAP_49
0     5.758190  3.941466  4.167144  4.003336
1     5.683244  3.897161  4.236626  4.700554
2     5.616856  4.123860  4.316325  4.545956
3     5.584971  3.985164  4.272292  4.703504
4     5.753873  3.981457  4.376808  4.781450
...        ...       ...       ...       ...
4247  5.556304  4.134521  4.193722  4.749475
4248  5.698370  4.081396  4.533859  4.391840
4249  5.784575  4.069282  4.284584  4.521476
4250  5.742706  3.873206  4.391310  4.741801
4251  5.783534  3.916183  4.171805  4.064209

[4252 rows x 53 columns]

In [ ]:
# create feature using tf-idf 1000 column

In [ ]:
# drop label cnt
train_df.drop(['label_cnt'], axis=1, inplace=True)

In [ ]:
train_df.tail(30)

                                                   text    label     UMAP_0  \
4222  Terlalu Banyak Lihat Catatan Saat Debat Cak Im...  Politik   9.907032
4223  prabowo Rakyat Berebut Bingkisan Anies Rakyat ...  Politik   9.787403
4224  PRESIDEN JOKOWI GA TAHU MALU GA PUNYA FATSUM P...  Politik   9.822333
4225  Bro kalo lo mau pilihan yang beda buat Pilpres...  Politik   9.597383
4226  Nelayan Indonesia nggak bisa terus terjebak da...  Politik  10.049279
4227  Dalam visinya Ganjar Pranowo dan Mahfud berupa...  Politik   9.714923
4228  Anies Baswedan berkunjung ke kediaman raja dan...  Politik   9.977116
4229  Pastikan kamu sekeluarga datang ke Tempat Pemu...  Politik   9.947724
4230  Capres Cawapres Ganjar Pranowo Mahfud Mahfud s...  Politik   9.451355
4231  Keberhasilan Pertahanan dan kemakmuran ekonomi...  Politik   9.799691
4232  Joget joget memang bisa menyenangkan tapi pemu...  Politik   9.683279
4233  Siap mendukung Pak Prabowo biar tidak ada koru...  Politik   9.992925
4234  Melalui Ganjar Mahfud Rebound Ganjar Pranowo d...  Politik   9.790432
4235  Pedagang bakso di bekasi dukung program progra...  Politik  10.027711
4236  FYI bro and sis Gua demen banget denger cerita...  Politik  10.194958
4237  Ganjar Pranowo pembela pekerja migran Kesejaht...  Politik   9.597482
4238  Pak Anies Baswedan paham sejarah Layak dipilih...  Politik  10.149305
4239  Dih bang Fahri Hamzah lagi ngomongin pak Jokow...  Politik  10.427978
4240  AKHIRNYAAAAAAA ada lagi adsnya abah ini bukan ...  Politik  10.236805
4241  Food Estate 600 H Akan Panen 1 e H Yang Benar ...  Politik  10.137110
4242  Oke gas oke gas tambah torang gas Full version...  Politik  10.085547
4243  Ahok nahan diri ga ikut kampanye Ganjar karena...  Politik  10.287246
4244  Dukungan tanpa pamrih dari Jawa Barat untuk Pr...  Politik  10.145503
4245  Ads Videotron Abah Anies di depan Hotel Sahid ...  Politik  10.180096
4246  Bener bener kejutan di awal tahun Khofifah res...  Politik   9.828342
4247  Anies apresiasi jasa pendidik dengan bebaskan ...  Politik  10.387262
4248  Anies Bansos Diberikan Ikut Kalender Kebutuhan...  Politik   9.985639
4249  Anies nothing to lose harus total war targetny...  Politik  10.184848
4250  Closing Statement pak Anies di acara KADIN sem...  Politik  10.255561
4251  Capres nomor urut 3 Ganjar Pranowo menanggapi ...  Politik   9.867221

         UMAP_1    UMAP_2    UMAP_3    UMAP_4    UMAP_5    UMAP_6    UMAP_7  \
4222   9.856419  0.130944  6.787336  7.785984  3.054758  4.708285  5.915683
4223   9.651882  0.283344  5.745153  8.352692  2.729614  4.608505  6.001389
4224  10.139477  0.060839  8.076361  7.887089  1.717405  4.759866  6.286457
4225   9.498289  0.338795  4.763514  8.640994  2.675228  4.612290  5.935198
4226   9.442733  0.132276  3.986048  8.673738  2.919468  4.776862  6.233314
4227   9.488522  0.410304  4.937451  8.654007  2.706590  4.772424  6.161055
4228  10.201573  0.336225  8.582481  7.212720  3.491653  4.489577  6.049974
4229   9.696565  0.355097  5.388226  8.483684  2.515249  4.923838  6.018271
4230   9.302345  0.212341  4.664021  8.728395  3.021126  4.613434  6.041794
4231   9.654040  0.360209  6.292895  8.472958  2.272824  4.756835  6.524645
4232   0.878072  0.019283  4.851286  9.313082  2.653370  4.683784  5.483314
4233  10.083037 -0.023555  7.978835  7.685135  2.263752  4.570991  6.057567
4234   9.580249  0.356683  5.511385  8.534980  2.586611  4.780554  6.227130
4235   9.807850  0.416710  7.235659  7.794719  2.272848  4.783022  5.762475
4236   9.844687 -0.052002  7.134159  7.690780  3.218653  4.545030  5.429655
4237   9.356160  0.395938  4.520002  8.691975  2.754817  4.712309  6.147920
4238   9.826742  0.206267  7.867296  7.387745  2.758648  4.663620  5.183546
4239   9.886206 -0.432102  7.364956  7.604475  3.632356  4.501573  5.071287
4240   9.813654 -0.027629  6.923741  7.773614  3.254904  4.589720  5.385362
4241  10.160072 -0.434187  7.551671  7.674318  2.550050  4.821857  5.622898
4242   9.968202  0.365989  8.130172  7.526526  1.999858  4.865791  5.600254
4243   9.835078 -0.492550  7.440626  7.613353  2.694949  4.689053  4.933291
4244   9.814036  0.491300  9.089620  6.366375  4.865646  3.833923  5.098829
4245   9.921331 -0.210099  7.077606  7.651798  3.124865  4.341568  5.413744
4246   9.877431  0.226815  7.105545  7.714766  3.006539  4.611356  6.078380
4247   9.814626 -0.592902  6.588658  7.837945  3.072002  4.253153  5.204512
4248  10.182143  0.331997  8.548603  7.233951  3.487427  4.487564  6.041484
4249   9.893972 -0.324297  7.296128  7.709228  2.882507  4.627234  5.313332
4250   9.697439  0.187231  7.165528  7.542428  3.648569  4.483389  5.383350
4251   9.735977  0.346649  6.276313  8.266153  2.490643  4.940298  6.299582

      ...   UMAP_40   UMAP_41   UMAP_42   UMAP_43   UMAP_44   UMAP_45  \
4222  ...  5.699809  5.097166  4.123531  4.876035  5.188938  4.575157
4223  ...  5.527527  5.553497  4.135731  4.494321  4.987338  4.589360
4224  ...  5.265729  5.442179  4.280860  4.965253  5.114721  4.458837
4225  ...  5.640307  5.384919  4.113315  4.263026  4.955980  4.584454
4226  ...  5.112857  5.325449  4.215791  4.430916  5.084078  4.683907
4227  ...  5.530143  5.485908  4.142481  4.339142  4.913864  4.623344
4228  ...  5.914614  5.275473  4.181566  4.728664  4.872864  4.563596
4229  ...  5.387300  5.448410  4.149146  4.381453  4.888261  4.584387
4230  ...  6.026203  5.306888  3.980989  4.421985  4.963719  4.625981
4231  ...  5.331028  5.957585  4.066663  4.546649  4.839425  4.653805
4232  ...  5.811755  5.522975  4.088793  4.078958  4.920475  4.471486
4233  ...  5.445877  5.328432  4.263494  4.970430  5.109678  4.463875
4234  ...  5.456055  5.652632  4.096974  4.446885  4.903647  4.635051
4235  ...  5.425681  5.346766  4.139588  4.564673  5.006485  4.434637
4236  ...  5.672512  5.400021  4.209748  5.033544  5.204506  4.502939
4237  ...  5.493904  5.384932  4.166450  4.246746  4.957173  4.597227
4238  ...  5.622018  5.168174  4.189600  5.017519  5.336780  4.385662
4239  ...  5.601214  5.574829  4.189730  5.062076  5.084922  4.551564
4240  ...  5.673865  5.386438  4.229976  5.022448  5.202495  4.512773
4241  ...  5.475419  5.246774  3.942546  4.898477  4.991356  4.518128
4242  ...  5.400986  5.347774  4.129690  4.660365  5.010307  4.388798
4243  ...  5.501183  5.592952  4.023881  5.084641  5.271196  4.367095
4244  ...  5.798023  4.997968  4.210485  4.498838  5.260234  4.402419
4245  ...  5.641280  5.119430  4.314758  5.029234  5.242657  4.399155
4246  ...  5.736153  5.093413  4.117885  4.786005  5.116826  4.579581
4247  ...  5.298098  5.211567  4.310747  4.916460  5.132716  4.401878
4248  ...  5.908797  5.259470  4.191670  4.736769  4.890192  4.559519
4249  ...  5.670415  5.492138  4.054288  4.922271  5.117767  4.422387
4250  ...  5.756721  5.083270  4.382019  5.115443  5.356683  4.493793
4251  ...  5.274796  5.843657  4.033881  4.585065  4.907177  4.654047

       UMAP_46   UMAP_47   UMAP_48   UMAP_49
4222  5.639381  3.867554  4.421518  4.422767
4223  5.850401  3.847047  4.211910  4.176052
4224  5.467912  4.082593  4.176373  4.331914
4225  5.943442  3.820768  4.246159  4.111633
4226  5.569173  4.058550  4.275013  4.296654
4227  5.885924  3.841536  4.216549  4.038411
4228  5.700166  4.095073  4.538276  4.377309
4229  5.809335  4.041523  4.235238  4.178777
4230  6.013624  3.578164  4.321131  3.972922
4231  5.750117  3.898814  4.149580  4.028978
4232  6.046086  4.155105  4.281166  4.175410
4233  5.525060  4.046277  4.290427  4.459033
4234  5.844042  3.865541  4.196094  4.073546
4235  5.787771  4.025996  4.361846  4.316226
4236  5.761347  4.000092  4.295509  4.573149
4237  5.863182  3.807839  4.227026  3.983947
4238  5.776808  3.952617  4.380606  4.634742
4239  5.824668  4.184351  4.213235  4.681729
4240  5.782004  3.988863  4.276937  4.585142
4241  5.576869  3.988917  4.337187  4.440378
4242  5.767542  4.092211  4.376348  4.393125
4243  5.810396  4.086827  4.198726  4.624083
4244  5.756627  4.004733  4.677054  4.621924
4245  5.586226  4.080251  4.370763  4.693060
4246  5.659804  3.829690  4.450983  4.341823
4247  5.556304  4.134521  4.193722  4.749475
4248  5.698370  4.081396  4.533859  4.391840
4249  5.784575  4.069282  4.284584  4.521476
4250  5.742706  3.873206  4.391310  4.741801
4251  5.783534  3.916183  4.171805  4.064209

[30 rows x 52 columns]

In [ ]:
# Label distribution
label_counts = {
    'Politik': 2858,
    'Sosial Budaya': 391,
    'Ekonomi': 267,
    'Pertahanan dan Keamanan': 263,
    'Ideologi': 258,
    'Sumber Daya Alam': 140,
    'Demografi': 56,
    'Geografi': 19
}

# Calculate weights (inverse of frequency)
total_samples = sum(label_counts.values())
weights = {label: total_samples / count for label, count in label_counts.items()}

# Normalize weights
max_weight = max(weights.values())
weights = {label: weight / max_weight for label, weight in weights.items()}

# Create a mapping of labels to weights
label_mapping = {
    'Politik': 0,
    'Sosial Budaya': 1,
    'Ekonomi': 2,
    'Pertahanan dan Keamanan': 3,
    'Ideologi': 4,
    'Sumber Daya Alam': 5,
    'Demografi': 6,
    'Geografi': 7
}

class_weights = [weights[label] for label in label_mapping.keys()]

# mape label
train_df['label'] = train_df['label'].map(label_mapping)

In [ ]:
model_1 = CatBoostClassifier(
    text_features=['text'],
    loss_function='MultiClass',
    eval_metric='TotalF1',
    task_type="GPU",
    devices="0",
    verbose=0,
    random_state=42,
    class_weights=class_weights,
)


cv_method = RepeatedStratifiedKFold(n_splits=5, n_repeats=1, random_state=42)
cv_results_model_1 = cross_val_score(estimator=model_1,  X=train_df.drop(['label', 'label_cnt'], axis=1), y=train_df["label"], cv=cv_method,
                                     verbose=100, scoring='balanced_accuracy')

print("Model 1 - Balanced Accuracy scores: ")
print(cv_results_model_1)
print("Mean: ")
print(cv_results_model_1.mean().round(3))

[CV] START .....................................................................
[CV] END ................................ score: (test=0.462) total time=  10.6s
[Parallel(n_jobs=1)]: Done   1 tasks      | elapsed:   10.6s
[CV] START .....................................................................
[CV] END ................................ score: (test=0.507) total time=   9.4s
[Parallel(n_jobs=1)]: Done   2 tasks      | elapsed:   20.0s
[CV] START .....................................................................
[CV] END ................................ score: (test=0.464) total time=   9.5s
[Parallel(n_jobs=1)]: Done   3 tasks      | elapsed:   29.6s
[CV] START .....................................................................
[CV] END ................................ score: (test=0.476) total time=   9.7s
[Parallel(n_jobs=1)]: Done   4 tasks      | elapsed:   39.3s
[CV] START .....................................................................
[CV] END ................................ score: (test=0.481) total time=   9.9s
[Parallel(n_jobs=1)]: Done   5 tasks      | elapsed:   49.2s
[Parallel(n_jobs=1)]: Done   5 tasks      | elapsed:   49.2s
Model 1 - Balanced Accuracy scores:
[0.46229002 0.5073526  0.46432353 0.47645109 0.48072362]
Mean:
0.478

In [ ]:
# make all text lowercase
train_df['text'] = train_df['text'].str.lower()

In [ ]:
train_df.to_csv(f'{DATA_DIR}/train_indo_akmal.csv', index=False)